"""
Technical indicator calculation script (v2.0).

Computes standard crypto technical indicators using pandas_ta:
- RSI (Relative Strength Index)
- MACD (Moving Average Convergence Divergence)
- Bollinger Bands
- EMA (Exponential Moving Average, multi-length)
- ATR (Average True Range)
- Stochastic oscillator

New in v2.0:
- Network-aware exchange selection
- Category-aware signal interpretation
- Combined technical + categorical context via 'smart' action

All indicators are computed from OHLCV data fetched via ccxt.
Results are JSON-serializable for downstream consumption.
"""

import argparse
import json
import logging
import sys
from typing import Any, Dict, Optional

import pandas as pd
import pandas_ta as ta  # type: ignore[import-untyped]

# ------------------------------------------------------------------ #
# Local imports
# ------------------------------------------------------------------ #
# pylint: disable=import-error, wrong-import-position
sys.path.insert(0, __file__.rsplit("\\", 1)[0] if "\\" in __file__ else __file__.rsplit("/", 1)[0])
from utils import (  # noqa: E402
    logger,
    _normalize_symbol,
    _fetch_df,
    _s,
    _col,
    parse_common_args,
    get_network_env,
    detect_category,
    get_category_analysis_dimensions,
)


# ------------------------------------------------------------------ #
# Indicator computation helpers
# ------------------------------------------------------------------ #
def _attach_all_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """Attach all supported indicators to the DataFrame in-place.

    Args:
        df: OHLCV DataFrame with columns: timestamp, open, high, low, close, volume.

    Returns:
        The same DataFrame with indicator columns appended.

    Notes:
        - Column names are dynamically generated by pandas_ta and may include
          parameter suffixes (e.g. "MACD_12_26_9", "RSI_14").
          Use ``utils._col()`` to look them up safely.
        - Indicators append: RSI_14, MACD_*, BB_*, EMA_7/25/99, ATRr_14, STOCHk_*, STOCHd_*
    """
    df.ta.rsi(length=14, append=True)
    df.ta.macd(fast=12, slow=26, signal=9, append=True)
    df.ta.bbands(length=20, std=2, append=True)
    for ema_len in [7, 25, 99]:
        df.ta.ema(length=ema_len, append=True)
    df.ta.atr(length=14, append=True)
    df.ta.stoch(append=True)
    return df


# ------------------------------------------------------------------ #
# Action functions
# ------------------------------------------------------------------ #
def action_rsi(symbol: str, timeframe: str = "1d", limit: int = 200) -> str:
    """Compute RSI (Relative Strength Index) for a symbol.

    RSI measures momentum on a 0-100 scale:
    - RSI > 70: potentially overbought (sell signal)
    - RSI < 30: potentially oversold (buy signal)

    Args:
        symbol: Trading pair string (auto-normalized to BASE/USDT).
        timeframe: Candle interval. Default "1d".
        limit: Number of candles to use. Default 200.

    Returns:
        JSON string with keys: symbol, timeframe, rsi_14 (array of last 10 values),
        current_rsi, signal (overbought/oversold/neutral).
    """
    symbol = _normalize_symbol(symbol)
    df = _fetch_df(symbol, timeframe, limit)
    df.ta.rsi(length=14, append=True)

    rsi_col: Optional[str] = _col(df, "RSI")
    if rsi_col is None:
        raise RuntimeError("RSI column not found after computation. pandas_ta may have changed column naming.")

    current = _s(df[rsi_col].iloc[-1])
    recent = [_s(v) for v in df[rsi_col].tail(10).tolist()]

    if current is not None:
        if current > 70:
            signal = "overbought"
        elif current < 30:
            signal = "oversold"
        else:
            signal = "neutral"
    else:
        signal = "unknown"

    return json.dumps({
        "symbol": symbol,
        "timeframe": timeframe,
        "indicator": "RSI_14",
        "current_rsi": current,
        "recent_rsi": recent,
        "signal": signal,
        "interpretation": {
            "overbought": "RSI > 70 suggests overbought conditions; consider taking profits.",
            "oversold": "RSI < 30 suggests oversold conditions; potential buy opportunity.",
            "neutral": "RSI between 30-70 is neutral; no strong momentum signal.",
        }.get(signal, ""),
    }, indent=2, ensure_ascii=False)


def action_macd(symbol: str,
                 timeframe: str = "1d",
                 fast: int = 12,
                 slow: int = 26,
                 signal: int = 9) -> str:
    """Compute MACD (Moving Average Convergence Divergence).

    MACD shows trend direction and momentum:
    - MACD line > Signal line: bullish momentum
    - MACD line < Signal line: bearish momentum
    - Histogram > 0: bullish; < 0: bearish

    Args:
        symbol: Trading pair string (auto-normalized).
        timeframe: Candle interval. Default "1d".
        fast: Fast EMA period. Default 12.
        slow: Slow EMA period. Default 26.
        signal: Signal line period. Default 9.

    Returns:
        JSON string with keys: symbol, timeframe, macd_line, signal_line,
        histogram, trend (bullish/bearish).
    """
    symbol = _normalize_symbol(symbol)
    df = _fetch_df(symbol, timeframe, slow + 50)
    df.ta.macd(fast=fast, slow=slow, signal=signal, append=True)

    macd_col: Optional[str] = _col(df, "MACD")
    signal_col: Optional[str] = _col(df, "MACDs")
    hist_col: Optional[str] = _col(df, "MACDh")

    if macd_col is None or signal_col is None:
        raise RuntimeError("MACD columns not found. Check pandas_ta version.")

    macd_val = _s(df[macd_col].iloc[-1])
    signal_val = _s(df[signal_col].iloc[-1])
    hist_val = _s(df[hist_col].iloc[-1]) if hist_col else None

    if macd_val is not None and signal_val is not None:
        trend = "bullish" if macd_val > signal_val else "bearish"
    else:
        trend = "unknown"

    return json.dumps({
        "symbol": symbol,
        "timeframe": timeframe,
        "indicator": f"MACD_{fast}_{slow}_{signal}",
        "macd_line": macd_val,
        "signal_line": signal_val,
        "histogram": hist_val,
        "trend": trend,
        "interpretation": {
            "bullish": "MACD > Signal: bullish momentum. Consider long positions.",
            "bearish": "MACD < Signal: bearish momentum. Consider short or exit.",
        }.get(trend, ""),
    }, indent=2, ensure_ascii=False)


def action_bollinger(symbol: str, timeframe: str = "1d", length: int = 20, std: float = 2.0) -> str:
    """Compute Bollinger Bands.

    Bollinger Bands show volatility and potential reversal points:
    - Price near upper band: potentially overbought
    - Price near lower band: potentially oversold
    - Band squeeze (narrow): low volatility, potential breakout ahead

    Args:
        symbol: Trading pair string (auto-normalized).
        timeframe: Candle interval. Default "1d".
        length: Moving average period. Default 20.
        std: Standard deviation multiplier. Default 2.0.

    Returns:
        JSON string with keys: symbol, timeframe, upper, mid, lower,
        close, position (above_upper/within_bands/below_lower).
    """
    symbol = _normalize_symbol(symbol)
    df = _fetch_df(symbol, timeframe, length + 30)
    df.ta.bbands(length=length, std=std, append=True)

    close = _s(df["close"].iloc[-1])
    # pandas_ta Bollinger columns: BBU_<len>_<std>_<std>, BBM_..., BBL_...
    upper_col = _col(df, "BBU")
    mid_col = _col(df, "BBM")
    lower_col = _col(df, "BBL")

    if upper_col is None or mid_col is None or lower_col is None:
        raise RuntimeError("Bollinger Bands columns not found.")

    upper = _s(df[upper_col].iloc[-1])
    mid = _s(df[mid_col].iloc[-1])
    lower = _s(df[lower_col].iloc[-1])

    if close is not None and upper is not None and lower is not None:
        if close > upper:
            position = "above_upper"
        elif close < lower:
            position = "below_lower"
        else:
            position = "within_bands"
    else:
        position = "unknown"

    return json.dumps({
        "symbol": symbol,
        "timeframe": timeframe,
        "indicator": f"Bollinger_Bands_{length}_{std}",
        "upper_band": upper,
        "middle_band": mid,
        "lower_band": lower,
        "current_close": close,
        "position": position,
        "band_width": _s(upper - lower) if upper and lower else None,
        "interpretation": {
            "above_upper": "Price above upper band: overbought, watch for reversal.",
            "below_lower": "Price below lower band: oversold, potential bounce.",
            "within_bands": "Price within bands: normal volatility conditions.",
        }.get(position, ""),
    }, indent=2, ensure_ascii=False)


def action_all(symbol: str, timeframe: str = "1d", limit: int = 200) -> str:
    """Compute all supported technical indicators at once.

    This is the most comprehensive single-call analysis. It attaches
    RSI, MACD, Bollinger Bands, EMAs, ATR, and Stochastic to the
    latest candle and returns a full snapshot.

    Args:
        symbol: Trading pair string (auto-normalized).
        timeframe: Candle interval. Default "1d".
        limit: Number of candles to fetch. Default 200.

    Returns:
        JSON string with all indicator values for the most recent candle.
    """
    symbol = _normalize_symbol(symbol)
    df = _fetch_df(symbol, timeframe, limit)
    df = _attach_all_indicators(df)

    close = _s(df["close"].iloc[-1])

    # Dynamic column lookup (pandas_ta version-safe)
    rsi_col = _col(df, "RSI")
    macd_col = _col(df, "MACD")
    macds_col = _col(df, "MACDs")
    macdh_col = _col(df, "MACDh")
    bbu_col = _col(df, "BBU")
    bbm_col = _col(df, "BBM")
    bbl_col = _col(df, "BBL")
    atr_col = _col(df, "ATR")

    # Network and category context
    env = get_network_env()
    base_ticker = symbol.replace("/USDT", "")
    category_info = detect_category(base_ticker)
    dims = get_category_analysis_dimensions(category_info["category"])

    return json.dumps({
        "symbol": symbol,
        "timeframe": timeframe,
        "close": close,
        "rsi_14": _s(df[rsi_col].iloc[-1]) if rsi_col else None,
        "macd_line": _s(df[macd_col].iloc[-1]) if macd_col else None,
        "macd_signal": _s(df[macds_col].iloc[-1]) if macds_col else None,
        "macd_histogram": _s(df[macdh_col].iloc[-1]) if macdh_col else None,
        "bb_upper": _s(df[bbu_col].iloc[-1]) if bbu_col else None,
        "bb_middle": _s(df[bbm_col].iloc[-1]) if bbm_col else None,
        "bb_lower": _s(df[bbl_col].iloc[-1]) if bbl_col else None,
        "ema_7": _s(df.get("EMA_7", df.get("EMA_7_")).iloc[-1]) if "EMA_7" in df.columns or any("EMA_7" in c for c in df.columns) else None,
        "ema_25": _s(df.get("EMA_25", pd.Series([None])).iloc[-1]),
        "ema_99": _s(df.get("EMA_99", pd.Series([None])).iloc[-1]),
        "atr_14": _s(df[atr_col].iloc[-1]) if atr_col else None,
        "stoch_k": _s(df.get(_col(df, "STOCHk"), pd.Series([None])).iloc[-1]) if _col(df, "STOCHk") else None,
        "stoch_d": _s(df.get(_col(df, "STOCHd"), pd.Series([None])).iloc[-1]) if _col(df, "STOCHd") else None,
        "network_environment": env,
        "category": category_info,
        "category_analysis_hint": dims.get("narrative_check", ""),
    }, indent=2, ensure_ascii=False)


# ------------------------------------------------------------------ #
# CLI entry point
# ------------------------------------------------------------------ #
def build_parser() -> argparse.ArgumentParser:
    """Build CLI argument parser."""
    parser = argparse.ArgumentParser(
        description="Technical indicator calculator (Gate/OKX)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --action rsi --symbol BTC
  %(prog)s --action macd --symbol ETH --timeframe 4h
  %(prog)s --action bollinger --symbol SOL
  %(prog)s --action all --symbol BTC --timeframe 1d
""",
    )
    parser.add_argument(
        "--action", type=str, required=True,
        choices=["rsi", "macd", "bollinger", "all"],
        help="Indicator to compute.",
    )
    parser.add_argument("--symbol", type=str, default="BTC",
                        help="Trading pair (default: BTC/USDT)")
    parser.add_argument("--timeframe", type=str, default="1d",
                        help="Candle interval (default: 1d)")
    parser.add_argument("--limit", type=int, default=200,
                        help="Number of candles (default: 200)")
    return parser


def main() -> None:
    """CLI entry point."""
    parser = build_parser()
    args = parser.parse_args()

    try:
        if args.action == "rsi":
            print(action_rsi(args.symbol, args.timeframe, args.limit))
        elif args.action == "macd":
            print(action_macd(args.symbol, args.timeframe))
        elif args.action == "bollinger":
            print(action_bollinger(args.symbol, args.timeframe))
        elif args.action == "all":
            print(action_all(args.symbol, args.timeframe, args.limit))
        else:
            parser.error(f"Unknown action: {args.action}")
    except (ValueError, RuntimeError) as e:
        logger.error("Execution failed: %s", e)
        sys.exit(1)


if __name__ == "__main__":
    main()
